
package com.pelindo.ebtos.ejb.ws.client;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-hudson-28-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentBankingSync", targetNamespace = "http://ws.ebtos.pelindo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentBankingSync {


    /**
     * 
     * @param invoiceDate
     * @param charge
     * @param vesselName
     * @param vesselCode
     * @param custCode
     * @param serviceCode
     * @param noInvoice
     * @param currCode
     * @param custName
     * @param serviceName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createInvoice", targetNamespace = "http://ws.ebtos.pelindo.com/", className = "com.pelindo.ebtos.ejb.ws.client.CreateInvoice")
    @ResponseWrapper(localName = "createInvoiceResponse", targetNamespace = "http://ws.ebtos.pelindo.com/", className = "com.pelindo.ebtos.ejb.ws.client.CreateInvoiceResponse")
    @Action(input = "http://ws.ebtos.pelindo.com/PaymentBankingSync/createInvoiceRequest", output = "http://ws.ebtos.pelindo.com/PaymentBankingSync/createInvoiceResponse")
    public String createInvoice(
        @WebParam(name = "noInvoice", targetNamespace = "")
        String noInvoice,
        @WebParam(name = "custCode", targetNamespace = "")
        String custCode,
        @WebParam(name = "custName", targetNamespace = "")
        String custName,
        @WebParam(name = "vesselCode", targetNamespace = "")
        String vesselCode,
        @WebParam(name = "vesselName", targetNamespace = "")
        String vesselName,
        @WebParam(name = "serviceCode", targetNamespace = "")
        String serviceCode,
        @WebParam(name = "serviceName", targetNamespace = "")
        String serviceName,
        @WebParam(name = "currCode", targetNamespace = "")
        String currCode,
        @WebParam(name = "charge", targetNamespace = "")
        BigDecimal charge,
        @WebParam(name = "invoiceDate", targetNamespace = "")
        XMLGregorianCalendar invoiceDate);

    /**
     * 
     * @param paymentDate
     * @param noInvoice
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doPayment", targetNamespace = "http://ws.ebtos.pelindo.com/", className = "com.pelindo.ebtos.ejb.ws.client.DoPayment")
    @ResponseWrapper(localName = "doPaymentResponse", targetNamespace = "http://ws.ebtos.pelindo.com/", className = "com.pelindo.ebtos.ejb.ws.client.DoPaymentResponse")
    @Action(input = "http://ws.ebtos.pelindo.com/PaymentBankingSync/doPaymentRequest", output = "http://ws.ebtos.pelindo.com/PaymentBankingSync/doPaymentResponse")
    public Boolean doPayment(
        @WebParam(name = "noInvoice", targetNamespace = "")
        String noInvoice,
        @WebParam(name = "paymentDate", targetNamespace = "")
        XMLGregorianCalendar paymentDate);

    /**
     * 
     * @param noInvoice
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelInvoice", targetNamespace = "http://ws.ebtos.pelindo.com/", className = "com.pelindo.ebtos.ejb.ws.client.CancelInvoice")
    @ResponseWrapper(localName = "cancelInvoiceResponse", targetNamespace = "http://ws.ebtos.pelindo.com/", className = "com.pelindo.ebtos.ejb.ws.client.CancelInvoiceResponse")
    @Action(input = "http://ws.ebtos.pelindo.com/PaymentBankingSync/cancelInvoiceRequest", output = "http://ws.ebtos.pelindo.com/PaymentBankingSync/cancelInvoiceResponse")
    public Boolean cancelInvoice(
        @WebParam(name = "noInvoice", targetNamespace = "")
        String noInvoice);

}
