
package com.pelindo.ebtos.ejb.ws.client;

import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-hudson-28-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentBankingSyncService", targetNamespace = "http://ws.ebtos.pelindo.com/", wsdlLocation = "http://localhost:8080/PaymentBankingSyncService/PaymentBankingSync?WSDL")
public class PaymentBankingSyncService
    extends Service
{

    private final static URL PAYMENTBANKINGSYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYMENTBANKINGSYNCSERVICE_EXCEPTION;
    private final static QName PAYMENTBANKINGSYNCSERVICE_QNAME = new QName("http://ws.ebtos.pelindo.com/", "PaymentBankingSyncService");

    static {
        URL url = null;
        WebServiceException e = null;
        InputStream stream = null;
        Properties properties = null;
        String host = null;
        String port = null;

        try {
            ClassLoader loader = PaymentBankingSyncService.class.getClassLoader();
            stream = loader.getResourceAsStream("config.properties");
            properties = new Properties();
            properties.load(stream);
            host = properties.getProperty("eBTOSPaymentBankingHost");
            port = properties.getProperty("eBTOSPaymentBankingPort");
        } catch (IOException ioe) {
            host = "localhost";
            port = "8080";
        } finally {
            try {
                if (stream != null) {
                    stream.close();
                }
            } catch (IOException ex) {
                Logger.getLogger(PaymentBankingSyncService.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            url = new URL(String.format("http://%s:%s/PaymentBankingSyncService/PaymentBankingSync?WSDL", host, port));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }

        PAYMENTBANKINGSYNCSERVICE_WSDL_LOCATION = url;
        PAYMENTBANKINGSYNCSERVICE_EXCEPTION = e;
    }

    public PaymentBankingSyncService() {
        super(__getWsdlLocation(), PAYMENTBANKINGSYNCSERVICE_QNAME);
    }

    public PaymentBankingSyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTBANKINGSYNCSERVICE_QNAME, features);
    }

    public PaymentBankingSyncService(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTBANKINGSYNCSERVICE_QNAME);
    }

    public PaymentBankingSyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTBANKINGSYNCSERVICE_QNAME, features);
    }

    public PaymentBankingSyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentBankingSyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentBankingSync
     */
    @WebEndpoint(name = "PaymentBankingSyncPort")
    public PaymentBankingSync getPaymentBankingSyncPort() {
        return super.getPort(new QName("http://ws.ebtos.pelindo.com/", "PaymentBankingSyncPort"), PaymentBankingSync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentBankingSync
     */
    @WebEndpoint(name = "PaymentBankingSyncPort")
    public PaymentBankingSync getPaymentBankingSyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.ebtos.pelindo.com/", "PaymentBankingSyncPort"), PaymentBankingSync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTBANKINGSYNCSERVICE_EXCEPTION!= null) {
            throw PAYMENTBANKINGSYNCSERVICE_EXCEPTION;
        }
        return PAYMENTBANKINGSYNCSERVICE_WSDL_LOCATION;
    }

}
